save_dir: './saved_models'
save_name: 'CIFAR10_N1-1500_M1-3000_IBRL-100_IBRU-100_seed-0'
resume: false
load_path: null
overwrite: true

epoch: 1
num_train_iter: 1048576
num_eval_iter: 2500
batch_size: 64
uratio: 2
eval_batch_size: 1024

hard_label: true
T: 0.5
p_cutoff: 0.95
ema_m: 0.999
ulb_loss_ratio: 1.0
LA: false

lr: 0.03
momentum: 0.9
weight_decay: 0.0005
amp: true

net: 'WideResNet'
net_from_name: false
depth: 28
widen_factor: 2
leaky_slope: 0.1
bn_momentum: 0.001
dropout: 0.0

data_dir: './data'
dataset: 'cifar10'
train_sampler: 'RandomSampler'
num_classes: 10
num_workers: 1
imbalance_l: 100
imbalance_u: 100
N1: 1500
M1: 3000
include_train: false

world_size: 1
rank: 0
dist_url: 'tcp://127.0.0.1:10009'
dist_backend: 'nccl'
seed: 0
gpu: null
multiprocessing_distributed: true

wandb_project: 'ICML-CIFAR10-IBRLU-100-100'
wandb_entity: 'aaai-23'
wandb_runid: 'CIFAR10_N1-1500_M1-3000_IBRL-100_IBRU-100_seed-0'
