wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    code_path: code/pretrain.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.7
    start_time: 1712150317.4837
    t:
      1:
      - 1
      - 5
      - 41
      - 49
      - 51
      - 53
      - 55
      - 63
      2:
      - 1
      - 5
      - 41
      - 49
      - 51
      - 53
      - 55
      - 63
      3:
      - 14
      - 23
      4: 3.9.7
      5: 0.13.3
      8:
      - 5
      - 9
