save_dir: './saved_models'
save_name: 'stl10_N1-450_IBRL-10_IBRU-unk_seed-0'
resume: true
load_path: './saved_models/stl10_N1-450_IBRL-10_IBRU-unk_seed-0/model_iter:_250000_.pth'
overwrite: true

epoch: 1
num_train_iter: 1048576
num_eval_iter: 2500
batch_size: 64
uratio: 2
eval_batch_size: 1024

hard_label: true
T: 0.5
p_cutoff: 0.95
ema_m: 0.999
ulb_loss_ratio: 1.0
LA: false

lr: 0.03
momentum: 0.9
weight_decay: 0.0005
amp: true

net: 'wide_resnet28_2'
net_from_name: false
depth: 28
widen_factor: 2
leaky_slope: 0.1
bn_momentum: 0.001
dropout: 0.0

data_dir: './data'
dataset: 'stl10'
train_sampler: 'RandomSampler'
num_classes: 10
num_workers: 1
imbalance_l: 10
N1: 450
include_train: false
size: 32

world_size: 1
rank: 0
dist_url: 'tcp://127.0.0.1:10015'
dist_backend: 'nccl'
seed: 0
gpu: null
multiprocessing_distributed: true

wandb_project: 'ICML-STL10-IBRL-10'
wandb_entity: 'aaai-23'
wandb_runid: 'ICML-STL10-IBRL-10_seed-0'