# config.yaml
save_dir: './saved_models'
save_name: 'fixmatch'
resume: false
load_path: null
overwrite: false

epoch: 1
num_train_iter: 1048576
num_eval_iter: 10000
num_labels: 4000
batch_size: 64
uratio: 7
eval_batch_size: 1024

hard_label: true
T: 0.5
p_cutoff: 0.95
ema_m: 0.999
ulb_loss_ratio: 1.0
LA: false

lr: 0.03
momentum: 0.9
weight_decay: 0.0005
amp: false

net: 'WideResNet'
net_from_name: false
depth: 28
widen_factor: 2
leaky_slope: 0.1
bn_momentum: 0.001
dropout: 0.0

data_dir: './data'
dataset: 'cifar10'
train_sampler: 'RandomSampler'
num_classes: 10
num_workers: 1
imbalance_l: 1.0
imbalance_u: 1.0
N1: 1
M1: 1
include_train: false

world_size: -1
rank: -1
dist_url: 'tcp://127.0.0.1:10001'
dist_backend: 'nccl'
seed: 0
gpu: null
multiprocessing_distributed: false

wandb_project: 'FixMatch'
wandb_entity: 'stablegradients'
wandb_runid: 'maxmin_recall'